# Katkıda bulunma {#sec-contributing}

Bu kitap açık biçimde geliştirildi ve katkılarınız olmasaydı bugünkü niteliğine ulaşamazdı.
Kitabı daha da iyi hâle getirmeye birkaç yolla yardımcı olabilirsiniz:

-   Bir noktayı anlamadıysanız veya Türkçe anlatımı belirsiz bulduysanız [bir sorun kaydı açın](https://github.com/TerekliTahaBerk/r4ds-2e-tr/issues/new).
    Kafa karıştıran ya da anlaşılması güç yerler hakkındaki geri bildiriminiz değerlidir.

-   Bir yazım veya çeviri hatası fark ederseniz ilgili kaynak sayfayı düzenleyip pull request gönderebilirsiniz.
    Bunu daha önce yapmadıysanız süreç oldukça basittir:

    -   Kenar çubuğundaki **Bu sayfayı düzenle** bağlantısına tıklayın.

    -   GitHub'ın sayfa içi düzenleyicisinde değişikliklerinizi yapıp kaydedin.

    -   Bir pull request gönderin ve değişikliklerinizi kısaca açıklayın.
        “Yazım hatalarını düzelttim” demeniz yeterlidir.

    -   Önemli değişiklikler yaptıysanız şu ifadeyi ekleyin: “I assign the copyright of this contribution to Hadley Wickham”.
        Basılı kitabın telif süreci için bu beyan gereklidir.

Güvenlik açığı veya Davranış Kuralları ihlali gibi kamuya açık paylaşılmaması gereken konuları [terekli@tahaberk.com](mailto:terekli@tahaberk.com) adresine bildirin.
