name: Quarto kitabını oluştur ve yayımla

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu al
        uses: actions/checkout@v4

      - name: Quarto'yu kur
        uses: quarto-dev/quarto-actions/setup@v2

      - name: R'ı kur
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: R bağımlılıklarını kur
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Quarto projesini işle
        run: quarto render

      - name: Yayın çıktısını yükle
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
        with:
          path: _book/

  deploy:
    if: github.event_name != 'pull_request'
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Pages'a yayımla
        id: deployment
        uses: actions/deploy-pages@v4
